# Special Vector/Matrix/Tensor Operations, Attributes and Built-in Methods

In [1]:
import numpy as np
import scipy
import sympy
import tensorflow as tf
import torch
import random

from scipy import linalg
from sympy.vector import CoordSys3D
from sympy.vector import Vector
from sympy.interactive.printing import init_printing
from sympy.matrices import Matrix, eye, zeros, ones, diag, GramSchmidt
from sympy import Array

# Vector Operations

## Numpy

In [2]:
v1 = np.array([5, 4, 2, 2])
v2 = np.array([1, 1, 3, 3])
v3 = np.array([[np.random.randint(0, 100) for _ in range(3)]]) # vertical vector
v4 = np.array([[np.random.randint(-50, 0) for _ in range(3)]]) # vertical vector

In [3]:
# Dot Product of vectors
print(f"Dot product v1 and v2 = {v1.dot(v2)}")

Dot product v1 and v2 = 21


In [4]:
#Cross Product
print(f"Cross Product v3-v4: {np.cross(v3, v4)}")

Cross Product v3-v4: [[   0 -424  424]]


In [5]:
#Magnitude/Length of the vector
print(f"Magnitude of the vector v4: {np.linalg.norm(v4)}")

Magnitude of the vector v4: 24.041630560342615


## Sympy

In [6]:
N = CoordSys3D('N')

In [7]:
# Define a vector with basevectors
v1 = 2 * N.i + 5 * N.j
v2 = -3 * N.i - 2 * N.j

w1 = 4 * N.i + 2 * N.j - 3 * N.k
w2 = -5 * N.i - 2 * N.j + 9 * N.k

In [8]:
# Dot Product of vectors
print(f"Dot Product v1 and v2: {v1.dot(v2)}")

Dot Product v1 and v2: -16


In [9]:
# Cross Product of vectors
print(f"Cross Product of w1 and w2: {w1.cross(w2)}")

Cross Product of w1 and w2: 12*N.i + (-21)*N.j + 2*N.k


In [10]:
# Magnitude and normalization to have a 1 magnitude
print(f"Magnitude/Length of a vector: {v1.magnitude()}")
print(f"Normalization: {v1.normalize()}")

Magnitude/Length of a vector: sqrt(29)
Normalization: (2*sqrt(29)/29)*N.i + (5*sqrt(29)/29)*N.j


# Matrix Operations

## Numpy

In [11]:
A_array = np.random.randint(5, 30, size=(3, 3))
A_matrix = np.matrix([[2, 5, 6], [5, 7, 8], [12, 15, 22]], dtype="int")
B = np.random.randint(5, 30, size=(2, 3))
C = np.random.randint(5, 30, size=(2, 3))
D = np.random.randint(5, 30, size=(3, 2))

In [12]:
# Matrix multiplication element-wise at same shape
print(f"Matrix multiplication element-wise at same shape matrices: B * C = \n{B * C}")

Matrix multiplication element-wise at same shape matrices: B * C = 
[[280 180 104]
 [120  66 442]]


In [13]:
# Matrix multiplication
C @ D
#or
np.matmul(C, D)

array([[658, 985],
       [588, 713]])

In [14]:
# Transpose of a Matrix
C.T

array([[10,  8],
       [20,  6],
       [13, 17]])

In [15]:
# Inverse of a Matrix
try:
    A_array.I
except:
    print("Numpy Array doesn't have inverse attribute")
    print("Trying Linalg\n")
    print(linalg.inv(A_matrix))

Numpy Array doesn't have inverse attribute
Trying Linalg

[[-0.60714286  0.35714286  0.03571429]
 [ 0.25        0.5        -0.25      ]
 [ 0.16071429 -0.53571429  0.19642857]]


In [16]:
# Inverse of a Matrix (method 2)
A_matrix.I

matrix([[-0.60714286,  0.35714286,  0.03571429],
        [ 0.25      ,  0.5       , -0.25      ],
        [ 0.16071429, -0.53571429,  0.19642857]])

In [17]:
# Calculate Determinant of a Matrix 
print(f"Calculating Determinant of matrix A: {linalg.det(A_matrix)}")

Calculating Determinant of matrix A: -56.0


In [18]:
# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = linalg.eig(A_matrix)

In [19]:
eigenvalues

array([31.10286906+0.j, -1.3942385 +0.j,  1.29136944+0.j])

In [20]:
eigenvectors

array([[-0.24653765, -0.91712674, -0.17621159],
       [-0.35097351,  0.25182041, -0.74586549],
       [-0.90334754,  0.30897414,  0.64236606]])

### Useful built-in methods in Numpy

In [21]:
C

array([[10, 20, 13],
       [ 8,  6, 17]])

In [22]:
# Returning max value index in a given axis
C.argmax(axis=None) #axis=0 col-wise, axis=1 row-wise

1

In [23]:
# Returning max value based on argmax index
C.flatten()[C.argmax()]

20

In [24]:
# Returns the indices that would sort this array
C.argsort(axis=None) #axis=0 col-wise, axis=1 row-wise

array([4, 3, 0, 2, 5, 1], dtype=int64)

In [25]:
# Return selected slices of this array along given axis
np.choose([1, 0, 1], C)

array([ 8, 20, 17])

In [26]:
# Useful 1D iterator on flattened matrix
for i in C.flat: 
    print(i)

10
20
13
8
6
17


In [27]:
# Return an array whose values are limited to given min-max
C.clip(22, 30)

array([[22, 22, 22],
       [22, 22, 22]])

In [28]:
# Returning Max, Mean, Min, Sum 
print(f"C matrix max: {C.max(axis=None)}")
print(f"C matrix mean: {C.mean(axis=None)}")
print(f"C matrix min: {C.min(axis=None)}")
print(f"C matrix sum: {C.sum(axis=None)}")
print(f"C matrix std: {C.std(axis=None)}")

C matrix max: 20
C matrix mean: 12.333333333333334
C matrix min: 6
C matrix sum: 74
C matrix std: 4.921607686744467


In [29]:
C.cumsum(axis=None) # cum sum along axis 1

array([10, 30, 43, 51, 57, 74])

In [30]:
# Return shape of matrix
C.shape

(2, 3)

In [31]:
# Resize array in place
C.resize(1, 6)

In [32]:
# Return the matrix as a (possibly nested) list
C.tolist()

[[10, 20, 13, 8, 6, 17]]

In [33]:
# Return diagonal of a matrix (easier to visualise at a square matrix)
A_matrix.diagonal()

matrix([[ 2,  7, 22]])

## Sympy

In [34]:
# Define Matrices
A = Matrix([[12, 25, 3], [24, 100, 1]])
B =  Matrix(3, 3, np.random.randint(0, 15, 9))
C = Matrix(4, 4, lambda i,j: 2 + (i-j))
D = Matrix(3, 3, np.random.randint(15, 50, 9))

In [35]:
# Matrix Multiplication (no element-wise at Sympy)
A @ B
# or A * B

Matrix([
[171,  527,  330],
[607, 1719, 1075]])

In [36]:
# Take transpose of a matrix
A.T

Matrix([
[12,  24],
[25, 100],
[ 3,   1]])

In [37]:
# Compute determinant of a matrix
D.det()

27211

In [38]:
D.inv()

Matrix([
[  986/27211,  881/27211, -1364/27211],
[-1267/27211,  165/27211,   980/27211],
[  356/27211, -841/27211,   777/27211]])

In [39]:
# Eigenvalues of a matrix with algebraic-multiplicity
C.eigenvals()

{4 - 2*I: 1, 4 + 2*I: 1, 0: 2}

In [40]:
# Eigenvectors of a matrix
C.eigenvects()

[(0,
  2,
  [Matrix([
   [ 1],
   [-2],
   [ 1],
   [ 0]]),
   Matrix([
   [ 2],
   [-3],
   [ 0],
   [ 1]])]),
 (4 - 2*I,
  1,
  [Matrix([
   [-2/13 - 3*I/13],
   [ 3/13 - 2*I/13],
   [   8/13 - I/13],
   [             1]])]),
 (4 + 2*I,
  1,
  [Matrix([
   [-2/13 + 3*I/13],
   [ 3/13 + 2*I/13],
   [   8/13 + I/13],
   [             1]])])]

### Basic Operations

In [41]:
D

Matrix([
[35, 17, 40],
[49, 46, 28],
[37, 42, 47]])

In [42]:
# Printing out matrix shape
D.shape

(3, 3)

In [43]:
# Accessing first column
D.col(0)

Matrix([
[35],
[49],
[37]])

In [44]:
# Accessing Last row
D.row(-1)

Matrix([[37, 42, 47]])

In [45]:
# Deleting row/column
D.col_del(0)
D.row_del(-1)

In [46]:
D

Matrix([
[17, 40],
[46, 28]])

# Special matrices

In [47]:
#quadratic, identity, diagonal

### Square Matrix

In [48]:
np.random.randint(200, 500, size=(3, 3))

array([[469, 300, 316],
       [394, 414, 259],
       [332, 467, 319]])

In [49]:
Matrix(3, 3, np.random.randint(15, 50, 9))

Matrix([
[27, 15, 28],
[21, 27, 39],
[15, 27, 43]])

### Diagonal Matrix

In [50]:
np.diag(random.sample(range(1, 50), 10))

array([[49,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 25,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 16,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 38,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  7,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 24,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 15,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 47,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  6,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 41]])

In [51]:
sympy.diag(1, 2, 3, 4, 5)

Matrix([
[1, 0, 0, 0, 0],
[0, 2, 0, 0, 0],
[0, 0, 3, 0, 0],
[0, 0, 0, 4, 0],
[0, 0, 0, 0, 5]])

### Matrix with zeros

In [52]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [53]:
sympy.zeros(2, 3)

Matrix([
[0, 0, 0],
[0, 0, 0]])

### Matrix with ones

In [54]:
# NP ones
np.ones([5, 3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [55]:
sympy.ones(5, 3)

Matrix([
[1, 1, 1],
[1, 1, 1],
[1, 1, 1],
[1, 1, 1],
[1, 1, 1]])

### Identity Matrix

In [56]:
np.identity(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [57]:
sympy.eye(4)

Matrix([
[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 1, 0],
[0, 0, 0, 1]])

# Tensor Operations

## TensorFlow

In [58]:
# Define Tensor
tensor_1 = tf.constant([
  [[0, 1, 2],
   [5, 6, 7]],
    
  [[10, 11, 12],
   [15, 16, 17]],
    
  [[20, 21, 22],
   [25, 26, 27]],])

tensor_2 = tf.random.uniform([3, 2, 3])

In [59]:
tensor_2

<tf.Tensor: shape=(3, 2, 3), dtype=float32, numpy=
array([[[0.682284  , 0.7704406 , 0.19622302],
        [0.4272715 , 0.5231029 , 0.6760553 ]],

       [[0.954105  , 0.37840784, 0.4245646 ],
        [0.14755952, 0.00603712, 0.17037284]],

       [[0.74958575, 0.43807006, 0.21536422],
        [0.8623172 , 0.31120074, 0.9008869 ]]], dtype=float32)>

In [60]:
print("Shape:", tensor_2.shape)

Shape: (3, 2, 3)


In [61]:
# Transpose of a Tensor
print("Transpose:\n", tf.transpose(tensor_2))

Transpose:
 tf.Tensor(
[[[0.682284   0.954105   0.74958575]
  [0.4272715  0.14755952 0.8623172 ]]

 [[0.7704406  0.37840784 0.43807006]
  [0.5231029  0.00603712 0.31120074]]

 [[0.19622302 0.4245646  0.21536422]
  [0.6760553  0.17037284 0.9008869 ]]], shape=(3, 2, 3), dtype=float32)


In [62]:
# Sum, Min, Max, Mean
print("Sum:", tf.reduce_sum(tensor_2, axis=None, keepdims=False))
print()
print("Min:", tf.reduce_min(tensor_2, axis=1, keepdims=True))
print()
print("Max:", tf.reduce_max(tensor_2, axis=0, keepdims=False))
print()
print("Mean:", tf.reduce_mean(tensor_2))

Sum: tf.Tensor(8.833849, shape=(), dtype=float32)

Min: tf.Tensor(
[[[0.4272715  0.5231029  0.19622302]]

 [[0.14755952 0.00603712 0.17037284]]

 [[0.74958575 0.31120074 0.21536422]]], shape=(3, 1, 3), dtype=float32)

Max: tf.Tensor(
[[0.954105  0.7704406 0.4245646]
 [0.8623172 0.5231029 0.9008869]], shape=(2, 3), dtype=float32)

Mean: tf.Tensor(0.4907694, shape=(), dtype=float32)


## PyTorch

In [63]:
tensor_1 = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
tensor_2 = torch.tensor([[[25, 2], [62, 13]], [[24, 42], [4, 1]]])
tensor_random = torch.rand([2, 5, 6])

In [64]:
tensor_1

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

In [65]:
tensor_1.shape

torch.Size([2, 2, 2])

In [66]:
# Transpose of a Tensor
print("Transpose:\n", tf.transpose(tensor_2))

Transpose:
 tf.Tensor(
[[[25 24]
  [62  4]]

 [[ 2 42]
  [13  1]]], shape=(2, 2, 2), dtype=int64)


In [67]:
tensor_2

tensor([[[25,  2],
         [62, 13]],

        [[24, 42],
         [ 4,  1]]])

In [68]:
# Sum, Min, Max, Mean
print("Sum:", torch.sum(tensor_2, axis=None, keepdims=False))
print()
print("Min:", torch.min(tensor_2, axis=1, keepdims=True).values) #if only values
print()
print("Max:", torch.max(tensor_2, axis=0, keepdims=False)) #return max values and indexes where the value(s) were found
print()
print("Mean:", torch.mean(tensor_2, dtype=torch.float)) #cast to float before mean, since float result!

Sum: tensor(173)

Min: tensor([[[25,  2]],

        [[ 4,  1]]])

Max: torch.return_types.max(
values=tensor([[25, 42],
        [62, 13]]),
indices=tensor([[0, 1],
        [0, 0]]))

Mean: tensor(21.6250)


In [69]:
# Matrix Multiplication
tensor_1 @ tensor_2
# OR
torch.matmul(tensor_1, tensor_2)

tensor([[[149,  28],
         [323,  58]],

        [[144, 216],
         [200, 302]]])