In [34]:
import numpy as np
import scipy
from scipy import linalg

# Creating Matrices

In [13]:
## Creating custom int
np.matrix([[2, 5, 6], [5, 7, 8], [12, 15, 22]], dtype="int")

matrix([[ 2,  5,  6],
        [ 5,  7,  8],
        [12, 15, 22]])

In [19]:
## Creating custom float
np.matrix([[2, 5, 6], [5, 7, 8], [12, 15, 22]], dtype="float")

matrix([[ 2.,  5.,  6.],
        [ 5.,  7.,  8.],
        [12., 15., 22.]])

In [32]:
## Creating random matrix/array int
np.random.randint(1, 15, size=(3, 3))

array([[ 9,  1,  6],
       [11,  3,  6],
       [ 8, 12,  9]])

In [33]:
## Creating random matrix/array flaot
np.random.rand(3, 3)

array([[0.78579075, 0.05446871, 0.13084778],
       [0.50594009, 0.41181573, 0.72842499],
       [0.20469154, 0.40016182, 0.03698282]])

# Matrix Operations

In [75]:
A = np.matrix([[12, 25, 3], [24, 100, 1]])
B =  np.matrix([[12, 25, 3], [24, 100, 1], [56, 120, 9]])

In [76]:
A

matrix([[ 12,  25,   3],
        [ 24, 100,   1]])

In [77]:
# Transpose
A.T

matrix([[ 12,  24],
        [ 25, 100],
        [  3,   1]])

In [78]:
# Inverse
A.I

matrix([[ 0.13646764, -0.03374125],
        [-0.03341112,  0.01827082],
        [ 0.06588878, -0.01729182]])

In [79]:
# Scaler multiplication
2 * A

matrix([[ 24,  50,   6],
        [ 48, 200,   2]])

In [81]:
# Matrix multiplication
A*B

matrix([[  912,  3160,    88],
        [ 2744, 10720,   181]])

In [87]:
# Useful 1D iterator on flattened matrix
for i in A.flat: 
    print(i)

12
25
3
24
100
1


### *But what if I try to run these operations on a 2d random NP array*

In [103]:
C = np.random.randint(5, 150, size=(4, 4))
D = np.random.randint(5, 150, size=(4, 5))

In [104]:
C

array([[ 33,  46,  55, 105],
       [ 55, 126, 114,  34],
       [ 44, 135, 121,  77],
       [ 21,  50,  32, 142]])

In [105]:
C.T

array([[ 33,  55,  44,  21],
       [ 46, 126, 135,  50],
       [ 55, 114, 121,  32],
       [105,  34,  77, 142]])

In [115]:
# Array doesn't have I
try:
    C.I
except:
    print("Array doesn't have I")
    print("Trying Linalg\n")
    print(linalg.inv(C))

Array doesn't have I
Trying Linalg

[[ 0.00805002  0.05684885 -0.06075828  0.01338221]
 [-0.03979069  0.01834111 -0.00678639  0.02871111]
 [ 0.0388853  -0.03697872  0.03582954 -0.03932784]
 [ 0.00405743 -0.00653213  0.00330069  0.00381626]]


In [120]:
# Array doesn't have I
try:
    C * D
except:
    print("Matrix multiplication doesn't work at arrays!")
    print("Trying Linalg\n")
    print(C.dot(D))

Matrix multiplication doesn't work at arrays!
Trying Linalg

[[16242 20311 12780 21398 15681]
 [25809 15308 20354 30779 28875]
 [27842 21911 23692 35284 31352]
 [16191 24176 13862 23523 14807]]


In [123]:
# Calculate Determinant
linalg.det(C)

6107809.999999999

In [132]:
# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = linalg.eig(C)

# Matrix methods numpy-scipy

In [165]:
C

array([[ 33,  46,  55, 105],
       [ 55, 126, 114,  34],
       [ 44, 135, 121,  77],
       [ 21,  50,  32, 142]])

In [166]:
C.argmax() ## max value index

15

In [167]:
C.flatten()[C.argmax()]

142

In [213]:
np.choose([0, 0, 0, 0], C) #index array to construct a new array

array([ 33,  46,  55, 105])

In [223]:
C.tolist()

[[33, 46, 55, 105], [55, 126, 114, 34], [44, 135, 121, 77], [21, 50, 32, 142]]

In [224]:
C.sum()

1190

In [225]:
C.mean()

74.375

In [226]:
C.cumsum(axis=1) # cum sum along axis 1

array([[ 33,  79, 134, 239],
       [ 55, 181, 295, 329],
       [ 44, 179, 300, 377],
       [ 21,  71, 103, 245]])

In [222]:
D.reshape(5, -1).shape

(5, 4)

# Special Matricies

## Vectors

In [228]:
v = np.array([5, 4, 2, 2])
w = np.array([1, 1, 3, 3])

In [229]:
3 * v

array([15, 12,  6,  6])

In [230]:
5 * w

array([ 5,  5, 15, 15])

In [237]:
v+w

array([6, 5, 5, 5])

In [239]:
# Dot Product of vectors
v.dot(w)

21

In [245]:
# Cross product
np.cross(np.array([[2, 4, 1]]), np.array([[5, 3, 2]]))

array([[  5,   1, -14]])

## Quadratic Matrix

In [283]:
np.random.randint(200, 500, size=(3, 3))

array([[322, 224, 330],
       [329, 473, 405],
       [479, 233, 270]])

## Diagonal Matrix

In [277]:
import random

In [281]:
np.diag(random.sample(range(1, 50), 10))

array([[21,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 30,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 20,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  7,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 24,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 31,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 44,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  3,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  5,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 35]])

## Identity Matrix

In [282]:
np.identity(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])