In [1]:
import numpy as np
import scipy
import sympy
import tensorflow as tf
import torch

from scipy import linalg
from sympy.vector import CoordSys3D
from sympy.vector import Vector
from sympy.interactive.printing import init_printing
from sympy.matrices import Matrix, eye, zeros, ones, diag, GramSchmidt
from sympy import Array

# Scalars

*Usin Numpy Library and sized scalars!:)*

https://numpy.org/doc/stable/reference/arrays.scalars.html

In [2]:
# Integers
print(np.int8(5))
print(np.int16(-252))
print(np.int32(250235))
print(np.int64(234124321412))

5
-252
250235
234124321412


In [3]:
# Unsigned Integers
print(np.uint8(5))
print(np.uint16(252))
print(np.uint32(250235))
print(np.uint64(234124321412))

5
252
250235
234124321412


In [4]:
# Float
print(np.float16(5.23))
print(np.float32(252.32))
print(np.float64(250235.5213))
print(np.longdouble(234124321412.123534))

5.23
252.32
250235.5213
234124321412.12354


In [5]:
# Complex
print(np.complex64(5.23))
print(np.complex128(252.32))

(5.23+0j)
(252.32+0j)


# Vectors

## Numpy
https://numpy.org/doc/stable/reference/generated/numpy.array.html

In [6]:
# Define a vector
v1 = np.array([5, 4, 2, 2])
v2 = np.array([1, 1, 3, 3])
v3 = np.array([[np.random.randint(0, 100)] for _ in range(5)]) # vertical vector

In [7]:
print(f"v1 vector: {v1}")
print(f"v2 vector: {v2}")
print()
print(f"v3 vector: \n{v3}")

v1 vector: [5 4 2 2]
v2 vector: [1 1 3 3]

v3 vector: 
[[22]
 [16]
 [45]
 [ 1]
 [24]]


In [8]:
# Sum and Subtraction
print(f"Sum of a scalar and vector: {v1} + 15 = {v1 + 15}")
print(f"Subtraction of a scalar and vector: 25 - {v2} = {25 - v2}")

print(f"Sum of two vectors: {v1} + {v2} = {v1 + v2}")
print(f"Subtraction of two vectors: {v1} - {v2} = {v1 - v2}")

Sum of a scalar and vector: [5 4 2 2] + 15 = [20 19 17 17]
Subtraction of a scalar and vector: 25 - [1 1 3 3] = [24 24 22 22]
Sum of two vectors: [5 4 2 2] + [1 1 3 3] = [6 5 5 5]
Subtraction of two vectors: [5 4 2 2] - [1 1 3 3] = [ 4  3 -1 -1]


In [9]:
# Multiplication and Division
print(f"Multiplication with a scalar: v1 * 5 = {v1 * 5}")
print(f"Division by a scalar: v2 / 5 = {v2 / 5}")

print(f"Multiplication of two vectors: v1 * v2 = {v1 * v2}")
print(f"Division of two vectors: v1 / v3 = {v2 / v1}")

Multiplication with a scalar: v1 * 5 = [25 20 10 10]
Division by a scalar: v2 / 5 = [0.2 0.2 0.6 0.6]
Multiplication of two vectors: v1 * v2 = [5 4 6 6]
Division of two vectors: v1 / v3 = [0.2  0.25 1.5  1.5 ]


In [10]:
# Slicing
v1[0:2]

array([5, 4])

### Sympy
https://docs.sympy.org/latest/modules/vector/index.html

In [11]:
N = CoordSys3D('N')

In [12]:
# Base vectors of the Cartesian Coordinate System
print(type(N.i))
print(type(N.j))
print(type(N.k))

<class 'sympy.vector.vector.BaseVector'>
<class 'sympy.vector.vector.BaseVector'>
<class 'sympy.vector.vector.BaseVector'>


In [13]:
# Define a vector with basevectors
v1 = 2 * N.i + 5 * N.j
v2 = -3 * N.i - 2 * N.j

w1 = 4 * N.i + 2 * N.j - 3 * N.k
w2 = -5 * N.i - 2 * N.j + 9 * N.k

In [14]:
v1

2*N.i + 5*N.j

In [15]:
w2

(-5)*N.i + (-2)*N.j + 9*N.k

In [16]:
# Sum and Subtraction - Mathematically scalars and vectors are different entities
print(f"Sum of two vectors: {v1} + {v2} = {v1 + v2}")
print(f"Subtraction of two vectors: {v1} - {v2} = {v1 - v2}")
print()
print(f"Sum of two vectors: {w1} + {w2} = {w1 + w2}")
print(f"Subtraction of two vectors: {w1} - {w2} = {w1 - w2}")

Sum of two vectors: 2*N.i + 5*N.j + (-3)*N.i + (-2)*N.j = (-1)*N.i + 3*N.j
Subtraction of two vectors: 2*N.i + 5*N.j - (-3)*N.i + (-2)*N.j = 5*N.i + 7*N.j

Sum of two vectors: 4*N.i + 2*N.j + (-3)*N.k + (-5)*N.i + (-2)*N.j + 9*N.k = (-1)*N.i + 6*N.k
Subtraction of two vectors: 4*N.i + 2*N.j + (-3)*N.k - (-5)*N.i + (-2)*N.j + 9*N.k = 9*N.i + 4*N.j + (-12)*N.k


In [17]:
# Zero vector
Vector.zero

0

# Matrices

## Numpy
https://numpy.org/doc/stable/reference/generated/numpy.matrix.html

In [18]:
## Creating custom int
np.matrix([[2, 5, 6], [5, 7, 8], [12, 15, 22]], dtype="int")

matrix([[ 2,  5,  6],
        [ 5,  7,  8],
        [12, 15, 22]])

In [19]:
## Creating custom float
np.matrix([[2, 5, 6], [5, 7, 8], [12, 15, 22]], dtype="float")

matrix([[ 2.,  5.,  6.],
        [ 5.,  7.,  8.],
        [12., 15., 22.]])

In [20]:
## Creating random matrix/array int
np.random.randint(1, 15, size=(3, 3))

array([[12, 11,  7],
       [ 1,  1,  9],
       [14,  7, 12]])

In [21]:
## Creating random matrix/array flaot
np.random.rand(3, 3)

array([[0.22867641, 0.59072529, 0.33917177],
       [0.40379988, 0.43977906, 0.75042528],
       [0.7212117 , 0.11790871, 0.30995   ]])

In [22]:
# Define Matrices
A = np.matrix([[12, 25, 3], [24, 100, 1]])
B =  np.matrix([[12, 25, 3], [24, 100, 1], [56, 120, 9]])
C = np.matrix([[3, 2, 1], [1, 2, 3]])

In [23]:
# Slicing a matrix
print(f"A matrix first element of first row: {A[0, 0]}")
print(f"B second row, last 2 column value: {B[1, 1:3]}")
print(f"B last row: {B[-1, :]}")

A matrix first element of first row: 12
B second row, last 2 column value: [[100   1]]
B last row: [[ 56 120   9]]


In [24]:
print(f"Matrix A: \n{A}")
print()
print(f"Scaler-Matrix Sum: 15 + A = \n{15 + A}")
print(f"Scaler-Matrix Subtraction: A - 3 = \n{A - 3}")
print()
print(f"Scaler-Matrix Multiplication: 5 * A = \n{5 * A}")
print(f"Scaler-Matrix Division: A / 5 = \n{A / 5}")

Matrix A: 
[[ 12  25   3]
 [ 24 100   1]]

Scaler-Matrix Sum: 15 + A = 
[[ 27  40  18]
 [ 39 115  16]]
Scaler-Matrix Subtraction: A - 3 = 
[[ 9 22  0]
 [21 97 -2]]

Scaler-Matrix Multiplication: 5 * A = 
[[ 60 125  15]
 [120 500   5]]
Scaler-Matrix Division: A / 5 = 
[[ 2.4  5.   0.6]
 [ 4.8 20.   0.2]]


In [25]:
print(f"Matrix A: \n{A}")
print(f"Matrix B: \n{B}")
print(f"Matrix C: \n{C}")
print()
print("--(element-wise) Operations--")
print()

print(f"Sum of A and C: A + C = \n{A + C}")
print(f"Subtraction of A and C: A - C = \n{A - C}")
print()
print(f"Matrix-Matrix Multiplication: A * B = \n{A * B}")
print(f"Matrix-Matrix Division: A / C = \n{A / C}")

Matrix A: 
[[ 12  25   3]
 [ 24 100   1]]
Matrix B: 
[[ 12  25   3]
 [ 24 100   1]
 [ 56 120   9]]
Matrix C: 
[[3 2 1]
 [1 2 3]]

--(element-wise) Operations--

Sum of A and C: A + C = 
[[ 15  27   4]
 [ 25 102   4]]
Subtraction of A and C: A - C = 
[[ 9 23  2]
 [23 98 -2]]

Matrix-Matrix Multiplication: A * B = 
[[  912  3160    88]
 [ 2744 10720   181]]
Matrix-Matrix Division: A / C = 
[[ 4.         12.5         3.        ]
 [24.         50.          0.33333333]]


In [26]:
# Matrix multiplication
np.matmul(A, B)
A @ B

matrix([[  912,  3160,    88],
        [ 2744, 10720,   181]])

In [27]:
# Slicing first column for example
A[:, 0]

matrix([[12],
        [24]])

## Sympy
https://docs.sympy.org/latest/modules/matrices/matrices.html

In [28]:
init_printing(use_unicode=False, wrap_line=False)

In [29]:
# Define Matrices
A = Matrix([[12, 25, 3], [24, 100, 1]])
B =  Matrix(3, 3, np.random.randint(0, 15, 9))
C = Matrix(2, 3, lambda i,j: 2 + (i-j))
D = Matrix(3, 3, np.random.randint(15, 50, 9))

In [30]:
B

[0   1   9]
[         ]
[12  13  7]
[         ]
[4   5   2]

In [31]:
# Slicing B matrix
B[1, 1]

In [32]:
# Sum (element-wise)
A + C 

[14  26   3]
[          ]
[27  102  2]

In [33]:
# Subtraction (element-wise)
A - C

[10  24  3]
[         ]
[21  98  0]

In [34]:
# Multiplication (element-wise)
A * B

[312   352   289]
[               ]
[1204  1329  918]

In [35]:
# Division (element-wise)
C * D.inv()

[101  -227   19]
[---  -----  --]
[450   450   75]
[              ]
[ 53  -187   14]
[---  -----  --]
[225   450   75]

In [36]:
# Matrix Multiplication
A @ B

[312   352   289]
[               ]
[1204  1329  918]

# Tensors

## Numpy
https://numpy.org/doc/stable/reference/generated/numpy.array.html

In [37]:
# Define Tensor (Tensor is like a collection of scalars, vectors, matrices in >2 dimension)
X = np.array([[[25, 12, 23], [3, 4, 5]], [[6, 7, 8], [213, 1, 2]]])
Y = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
Z = np.array([[[1, 2, 3], [5, 6, 5]], [[2, 5, 2], [15, 75, 12]]])

In [38]:
print(X)
print(type(X))

[[[ 25  12  23]
  [  3   4   5]]

 [[  6   7   8]
  [213   1   2]]]
<class 'numpy.ndarray'>


In [39]:
print(f"Sum of Two Tensors: X + Z = \n{X + Z}") # elementwise operation
print()
print(f"Subtraction of Two Tensors: X - Z = \n{X - Z}") # elementwise operation

Sum of Two Tensors: X + Z = 
[[[ 26  14  26]
  [  8  10  10]]

 [[  8  12  10]
  [228  76  14]]]

Subtraction of Two Tensors: X - Z = 
[[[ 24  10  20]
  [ -2  -2   0]]

 [[  4   2   6]
  [198 -74 -10]]]


In [40]:
print(f"Multiplication of Two Tensors: X * Z = \n{X * Z}") # elementwise operation
print()
print(f"Division of Two Tensors: X / Z = \n{X / Z}") # elementwise operation

Multiplication of Two Tensors: X * Z = 
[[[  25   24   69]
  [  15   24   25]]

 [[  12   35   16]
  [3195   75   24]]]

Division of Two Tensors: X / Z = 
[[[2.50000000e+01 6.00000000e+00 7.66666667e+00]
  [6.00000000e-01 6.66666667e-01 1.00000000e+00]]

 [[3.00000000e+00 1.40000000e+00 4.00000000e+00]
  [1.42000000e+01 1.33333333e-02 1.66666667e-01]]]


## Sympy
https://docs.sympy.org/latest/modules/tensor/index.html

In [41]:
# Define Tensor
A = Array([[[1, 2], [3, 4]], [[5, 6], [8, 9]], [[10, 11], [12, 13]]])
B = Array([[[14, 15], [1, 4]], [[5, 2], [6, 3]], [[1, 11], [5, 13]]])

In [42]:
A

[[1  2]  [5  6]  [10  11]]
[[    ]  [    ]  [      ]]
[[3  4]  [8  9]  [12  13]]

In [43]:
B

[[14  15]  [5  2]  [1  11]]
[[      ]  [    ]  [     ]]
[[1   4 ]  [6  3]  [5  13]]

In [44]:
# Sum of tensors
A+B

[[15  17]  [10  8 ]  [11  22]]
[[      ]  [      ]  [      ]]
[[4   8 ]  [14  12]  [17  26]]

In [45]:
# Subtraction of tensors
B-A

[[13  13]  [0   -4]  [-9  0]]
[[      ]  [      ]  [     ]]
[[-2  0 ]  [-2  -6]  [-7  0]]

In [46]:
A * 3

[[3  6 ]  [15  18]  [30  33]]
[[     ]  [      ]  [      ]]
[[9  12]  [24  27]  [36  39]]

In [47]:
B / 2

[[ 7   15/2]  [5/2   1 ]  [1/2  11/2]]
[[         ]  [        ]  [         ]]
[[1/2   2  ]  [ 3   3/2]  [5/2  13/2]]

## TensorFlow
https://www.tensorflow.org/guide/tensor

In [48]:
# Define Scalar
tf.constant(5)

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [49]:
# Define Vector
tf.constant([5, 6, 8, 10, 15.5])

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 5. ,  6. ,  8. , 10. , 15.5], dtype=float32)>

In [50]:
# Define Matrix
tf.constant([[1, 2], [3, 4], [5, 6]], dtype=tf.float16)

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [51]:
# Define Tensor
tensor_1 = tf.constant([
  [[0, 1, 2],
   [5, 6, 7]],
    
  [[10, 11, 12],
   [15, 16, 17]],
    
  [[20, 21, 22],
   [25, 26, 27]],])

tensor_2 = tf.constant([
  [[5, 3, 4],
   [7, 8, 9]],
    
  [[15, 13, 14],
   [17, 18, 19]],
    
  [[25, 23, 24],
   [27, 28, 29]],])

tensor_3 = tf.ones([3, 2, 3])
tensor_4 = tf.random.uniform([3, 2, 3])

In [52]:
tensor_1

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 0,  1,  2],
        [ 5,  6,  7]],

       [[10, 11, 12],
        [15, 16, 17]],

       [[20, 21, 22],
        [25, 26, 27]]])>

In [53]:
# Sum of Tensors (element-wise)
print(f"Sum of Tensors: tensor_1 + tensor_2 = \n{tf.add(tensor_1, tensor_2)}")

Sum of Tensors: tensor_1 + tensor_2 = 
[[[ 5  4  6]
  [12 14 16]]

 [[25 24 26]
  [32 34 36]]

 [[45 44 46]
  [52 54 56]]]


In [54]:
# Subtraction of Tensors (element-wise)
print(f"Subtraction of Tensors: tensor_1 + (-tensor_2) = \n{tf.add(tensor_1, -tensor_2)}")

Subtraction of Tensors: tensor_1 + (-tensor_2) = 
[[[-5 -2 -2]
  [-2 -2 -2]]

 [[-5 -2 -2]
  [-2 -2 -2]]

 [[-5 -2 -2]
  [-2 -2 -2]]]


In [55]:
# Multiplication of Tensors (element-wise)
print(f"Tensors elementwise multiplication: tensor_1 * tensor_2 = \n{tf.multiply(tensor_1, tensor_2)}")

Tensors elementwise multiplication: tensor_1 * tensor_2 = 
[[[  0   3   8]
  [ 35  48  63]]

 [[150 143 168]
  [255 288 323]]

 [[500 483 528]
  [675 728 783]]]


In [56]:
# Division of Tensors (element-wise)
print(f"Division of Tensors: tensor_1 / tensor_2 = \n{tf.divide(tensor_1, tensor_2)}")

Division of Tensors: tensor_1 / tensor_2 = 
[[[0.         0.33333333 0.5       ]
  [0.71428571 0.75       0.77777778]]

 [[0.66666667 0.84615385 0.85714286]
  [0.88235294 0.88888889 0.89473684]]

 [[0.8        0.91304348 0.91666667]
  [0.92592593 0.92857143 0.93103448]]]


In [57]:
tensor_matrix1 = tf.random.uniform([2, 3])
tensor_matrix2 = tf.random.uniform([3, 2])

In [58]:
print(f"Matrix multiplication: Matrix1 @ Matrix2 = \n{tf.matmul(tensor_matrix1, tensor_matrix2)}")

Matrix multiplication: Matrix1 @ Matrix2 = 
[[0.5376053  0.6236181 ]
 [0.12327376 0.14907436]]


In [59]:
tensor_matrix1 @ tensor_matrix2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.5376053 , 0.6236181 ],
       [0.12327376, 0.14907436]], dtype=float32)>

In [60]:
# Easily convert to numpy array
tensor_1.numpy()

array([[[ 0,  1,  2],
        [ 5,  6,  7]],

       [[10, 11, 12],
        [15, 16, 17]],

       [[20, 21, 22],
        [25, 26, 27]]])

## PyTorch
https://pytorch.org/docs/stable/tensors.html

In [61]:
torch.cuda.is_available()

True

In [62]:
tensor_1 = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
tensor_2 = torch.tensor([[[25, 2], [62, 13]], [[24, 42], [4, 1]]])
tensor_zeros = torch.zeros([2, 4], dtype=torch.int16)
tensor_random = torch.rand([2, 5, 6])

In [63]:
print(tensor_1)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [64]:
type(tensor_1)

torch.Tensor

In [65]:
cuda0 = torch.device('cuda:0')
torch.ones([2, 4], dtype=torch.float64, device=cuda0)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0', dtype=torch.float64)

In [66]:
# Sum of Tensors (element-wise)
print(f"Sum of Tensors: tensor_1 + tensor_2 = \n{tensor_1 + tensor_2}")

Sum of Tensors: tensor_1 + tensor_2 = 
tensor([[[26,  4],
         [65, 17]],

        [[29, 48],
         [11,  9]]])


In [67]:
# Subtraction of Tensors (element-wise)
print(f"Subtraction of Tensors: tensor_1 + (-tensor_2) = \n{tensor_1 - tensor_2}")

Subtraction of Tensors: tensor_1 + (-tensor_2) = 
tensor([[[-24,   0],
         [-59,  -9]],

        [[-19, -36],
         [  3,   7]]])


In [68]:
# Multiplication of Tensors (element-wise)
print(f"Tensors elementwise multiplication: tensor_1 * tensor_2 = \n{tensor_1 * tensor_2}")

Tensors elementwise multiplication: tensor_1 * tensor_2 = 
tensor([[[ 25,   4],
         [186,  52]],

        [[120, 252],
         [ 28,   8]]])


In [69]:
# Division of Tensors (element-wise)
print(f"Division of Tensors: tensor_1 / tensor_2 = \n{tensor_1 / tensor_2}")

Division of Tensors: tensor_1 / tensor_2 = 
tensor([[[0.0400, 1.0000],
         [0.0484, 0.3077]],

        [[0.2083, 0.1429],
         [1.7500, 8.0000]]])
