In [1]:
import numpy as np
import scipy
import sympy
import tensorflow as tf
import torch
import random
import jax
import jax.numpy as jnp


from jax import jit, grad, vmap, jacobian
from scipy import linalg
from sympy.vector import CoordSys3D
from sympy.vector import Vector
from sympy.interactive.printing import init_printing
from sympy.matrices import Matrix, eye, zeros, ones, diag, GramSchmidt
from sympy import Array

# Square Matrix

In [2]:
np.random.randint(200, 500, size=(3, 3))

array([[276, 245, 463],
       [300, 220, 387],
       [270, 331, 385]])

In [3]:
Matrix(3, 3, np.random.randint(15, 50, 9))

Matrix([
[19, 47, 36],
[30, 33, 43],
[29, 23, 39]])

# Diagonal Matrix

In [4]:
np.diag(random.sample(range(1, 50), 10))

array([[18,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  8,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  1,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 32,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  2,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 34,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 49,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 12,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 38]])

In [5]:
sympy.diag(1, 2, 3, 4, 5)

Matrix([
[1, 0, 0, 0, 0],
[0, 2, 0, 0, 0],
[0, 0, 3, 0, 0],
[0, 0, 0, 4, 0],
[0, 0, 0, 0, 5]])

# Matrix with zeros

In [6]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
sympy.zeros(2, 3)

Matrix([
[0, 0, 0],
[0, 0, 0]])

# Matrix with ones

In [8]:
# NP ones
np.ones([5, 3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
sympy.ones(5, 3)

Matrix([
[1, 1, 1],
[1, 1, 1],
[1, 1, 1],
[1, 1, 1],
[1, 1, 1]])

# Identity Matrix

In [10]:
np.identity(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [11]:
sympy.eye(4)

Matrix([
[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 1, 0],
[0, 0, 0, 1]])

# Triangular Matrix (upper)

In [12]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], k=-1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

In [13]:
A = Matrix([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
A.upper_triangular(-1)

Matrix([
[1, 2,  3],
[4, 5,  6],
[0, 8,  9],
[0, 0, 12]])

# Triangular Matrix (lower)

In [14]:
np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], k=0)

array([[ 1,  0,  0],
       [ 4,  5,  0],
       [ 7,  8,  9],
       [10, 11, 12]])

In [15]:
A = Matrix([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
A.lower_triangular(0)

Matrix([
[ 1,  0,  0],
[ 4,  5,  0],
[ 7,  8,  9],
[10, 11, 12]])